# bash completion for gt, generated by aargh (argh.h). Load it with:
#   source <(gt --completions bash)
_gt_cmds() {
    case "$1" in
        "") echo 'remote' ;;
        "remote") echo 'add' ;;
    esac
}
_gt_opts() {
    case "$1" in
        "") echo ' --color --no-color -w --when -o -h --help -V --version ' ;;
        "remote") echo ' --color --no-color -w --when -o -h --help -V --version ' ;;
        "remote add") echo ' --color --no-color -w --when -o -f --force -h --help -V --version ' ;;
    esac
}
_gt_takes() {
    case "$1|$2" in
        *"|-w"|*"|--when") return 0 ;;
        *"|-o") return 0 ;;
    esac
    return 1
}
_gt_values() {
    case "$1|$2" in
        *"|-w"|*"|--when") echo 'auto never' ;;
        *"|-o") echo '@file' ;;
    esac
}
_gt_files() {
    case "$1" in
        "remote add") return 0 ;;
    esac
    return 1
}
_gt() {
    local cur=${COMP_WORDS[COMP_CWORD]} prev=${COMP_WORDS[COMP_CWORD-1]} at= i w c v
    for ((i = 1; i < COMP_CWORD; i++)); do
        w=${COMP_WORDS[i]}
        case $w in
            --) break ;;
            -*=*) ;;
            -*) _gt_takes "$at" "$w" && i=$((i + 1)) ;;
            *) for c in $(_gt_cmds "$at"); do
                   if [[ $c == "$w" ]]; then at=${at:+$at }$w; break; fi
               done ;;
        esac
    done
    COMPREPLY=()
    if ((COMP_CWORD > 1)) && _gt_takes "$at" "$prev"; then
        v=$(_gt_values "$at" "$prev")
        if [[ $v == @file ]]; then
            COMPREPLY=($(compgen -f -- "$cur"))
        else
            COMPREPLY=($(compgen -W "$v" -- "$cur"))
        fi
    elif [[ $cur == -* ]]; then
        COMPREPLY=($(compgen -W "$(_gt_opts "$at")" -- "$cur"))
    else
        c=$(_gt_cmds "$at")
        if [[ -n $c ]]; then
            COMPREPLY=($(compgen -W "$c" -- "$cur"))
        elif _gt_files "$at"; then
            COMPREPLY=($(compgen -f -- "$cur"))
        fi
    fi
}
complete -F _gt gt
