# fish completion for gt, generated by aargh (argh.h). Load it with:
#   gt --completions fish | source
set -g __gt_cmds '|remote' 'remote|add'
set -g __gt_takes '|-w' '|--when' '|-o' 'remote|-w' 'remote|--when' 'remote|-o' 'remote add|-w' 'remote add|--when' 'remote add|-o'
function __gt_at
    set -l at ''
    set -l skip 0
    for w in (commandline -opc)[2..-1]
        if test $skip = 1
            set skip 0
            continue
        end
        switch $w
            case '--'
                break
            case '-*=*'
            case '-*'
                contains -- "$at|$w" $__gt_takes; and set skip 1
            case '*'
                if contains -- "$at|$w" $__gt_cmds
                    set at (string trim -- "$at $w")
                end
        end
    end
    test "$at" = "$argv[1]"
end
complete -c gt -e
complete -c gt -n "__gt_at ''" -l color -d 'Use color'
complete -c gt -n "__gt_at ''" -l no-color
complete -c gt -n "__gt_at ''" -s w -l when -d 'When it\'s done' -x -a 'auto never'
complete -c gt -n "__gt_at ''" -s o -d 'Output' -r
complete -c gt -n "__gt_at ''" -s h -l help -d 'Print help'
complete -c gt -n "__gt_at ''" -s V -l version -d 'Print version'
complete -c gt -n "__gt_at ''" -f -a remote -d 'Remotes'
complete -c gt -n "__gt_at ''" -f
complete -c gt -n "__gt_at 'remote'" -l color -d 'Use color'
complete -c gt -n "__gt_at 'remote'" -l no-color
complete -c gt -n "__gt_at 'remote'" -s w -l when -d 'When it\'s done' -x -a 'auto never'
complete -c gt -n "__gt_at 'remote'" -s o -d 'Output' -r
complete -c gt -n "__gt_at 'remote'" -s h -l help -d 'Print help'
complete -c gt -n "__gt_at 'remote'" -s V -l version -d 'Print version'
complete -c gt -n "__gt_at 'remote'" -f -a add -d 'Add one'
complete -c gt -n "__gt_at 'remote'" -f
complete -c gt -n "__gt_at 'remote add'" -l color -d 'Use color'
complete -c gt -n "__gt_at 'remote add'" -l no-color
complete -c gt -n "__gt_at 'remote add'" -s w -l when -d 'When it\'s done' -x -a 'auto never'
complete -c gt -n "__gt_at 'remote add'" -s o -d 'Output' -r
complete -c gt -n "__gt_at 'remote add'" -s f -l force -d 'Force'
complete -c gt -n "__gt_at 'remote add'" -s h -l help -d 'Print help'
complete -c gt -n "__gt_at 'remote add'" -s V -l version -d 'Print version'
